# Generated by Django 5.1.3 on 2025-07-22 13:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
    ]
