databases:
  - name: contactdb
    plan: free
    databaseName: contact_manager
    user: contacthub_user

services:
  - type: web
    plan: free
    name: contacthub
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn contacthub.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contactdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CLOUDINARY_CLOUD_NAME
        value: dukintvwx  # Not sensitive, can be in blueprint
      - key: CLOUDINARY_API_KEY
        value: 368642299415552  # Not highly sensitive, but could move to dashboard
      # CLOUDINARY_API_SECRET - Set this manually in Render dashboard for security